### ISSUE TITLE
Update installation section in README

### ISSUE THREAD

**Issue by Joshua-Anderson** [deis/workflow-cli#10] opened 2016-03-08 04:29 UTC
> Installation

> Currently the only way to use the go version of the deis client is to build it yourself. To build the deis client, you need to have go, glide, and make installed. Then run make build.

The [installation](https://github.com/deis/workflow-cli#installation) section of the README is way out of date and hasn't been updated since I wrote this over the summer. It's now the official client and we should add instructions for how to install it from deis.io and bintray.

**Comment by bacongobbler** [comment] 2016-03-08 04:59
dupe of #9 :)

**Closed by bacongobbler** 2016-03-08 04:59 UTC

**Comment by Joshua-Anderson** [comment] 2016-03-08 05:01
Whoops :frowning: 

I swear I looked for this issue. :smiley:
Glad to see that people already caught this!
